---
# nginx tasks/Debian.yml
#
# SPDX-FileCopyrightText: © 2020 Open Networking Foundation <support@opennetworking.org>
# SPDX-License-Identifier: Apache-2.0

- name: Install NGINX packages (Debian)
  apt:
    name: "{{ nginx_packages }}"
    state: "present"
    update_cache: true
    cache_valid_time: 3600
  notify:
    - start-nginx

- name: Enable NGINX Service
  service:
    name: "{{ nginx_service }}"
    enabled: true
