---
# nginx tasks/Debian.yml
#
# SPDX-FileCopyrightText: © 2020 Open Networking Foundation <support@opennetworking.org>
# SPDX-License-Identifier: Apache-2.0

# Docs: http://nginx.org/en/linux_packages.html
- name: Add NGINX apt repo key
  apt_key:
    data: "{{ lookup('file','nginx_signing.key') }}"
    state: "present"

- name: Add NGINX apt repo
  apt_repository:
    repo: >-
      deb http://nginx.org/packages/{{ ansible_lsb['id'] | lower }}
      {{ ansible_lsb['codename'] }} nginx
    update_cache: true

- name: Install NGINX packages (Debian)
  apt:
    name: "{{ nginx_packages }}"
    state: "present"
    update_cache: true
    cache_valid_time: 3600
  notify:
    - start-nginx

- name: Enable NGINX Service
  service:
    name: "{{ nginx_service }}"
    enabled: true
