---
# nginx molecule/default/prepare.yml
#
# SPDX-FileCopyrightText: © 2020 Open Networking Foundation <support@opennetworking.org>
# SPDX-License-Identifier: Apache-2.0

- name: Prepare
  hosts: all

  tasks:
  - name: Install GPG to support adding apt repo keys
    apt:
      name: "gpg"
      state: "present"
      update_cache: true
